# Ignore this, its just here so I don't lose it

version: '3'

services:
    mongo:
        image: mongo:latest
        ports:
            - "27016:27016"
        volumes:
            - ./data/mongo:/data/db
        env_file:
          - .env
        command: --port 27016
